### ISSUE TITLE
Segfault at startup

### ISSUE THREAD

**Issue by antonio-rojas** [c-koi/zart#14]
zart segfaults immediately at startup
```
#0  std::__atomic_base<int>::load(std::memory_order) const (__m=std::memory_order_relaxed, this=0x0) at /usr/include/c++/9.3.0/bits/atomic_base.h:419
#1  QAtomicOps<int>::loadRelaxed<int>(std::atomic<int> const&) (_q_value=...) at /usr/include/qt/QtCore/qatomic_cxx11.h:239
#2  0x000055555558cafe in QBasicAtomicInteger<int>::loadRelaxed() const (this=0x0) at /usr/include/qt/QtCore/qbasicatomic.h:107
#3  0x0000555555584914 in QtPrivate::RefCount::deref() (this=0x0) at /usr/include/qt/QtCore/qrefcount.h:66
#4  0x000055555558d345 in QList<int>::~QList() (this=0x7fffffffdc40, __in_chrg=<optimized out>) at /usr/include/qt/QtCore/qlist.h:873
#5  0x00005555555befdf in QList<int>::operator=(QList<int>&&) (this=0x555555830658 <WebcamSource::_webcamList>, other=...)
    at /usr/include/qt/QtCore/qlist.h:167
#6  0x00005555555be77e in QList<int>::clear() (this=0x555555830658 <WebcamSource::_webcamList>) at /usr/include/qt/QtCore/qlist.h:930
#7  0x00005555555b8046 in WebcamSource::getWebcamList() () at src/WebcamSource.cpp:118
#8  0x0000555555578870 in MainWindow::MainWindow(QWidget*) (this=0x7fffffffe080, parent=0x0) at src/MainWindow.cpp:159
#9  0x0000555555590700 in main(int, char**) (argc=1, argv=0x7fffffffe5a8) at src/ZArt.cpp:106
```
stdout:
```
[Device 0] is a capture
[Device 0] is a camera
[Device 1] is a capture
[ static const QList<int>& WebcamSource::getWebcamList() ] _webcamList = (0)
[ static void WebcamSource::retrieveWebcamResolutionsV4L2(const QList<int>&) ] <<Entering>>
[Device 0] is a camera
[Device 0] pixel format MJPG
[Device 0] pixel format YUYV
Done checking resolutions
```

**Comment by dtschump** [comment]
What version did you use ? Is it the latest sources in the git repo ?

**Comment by antonio-rojas** [comment]
Commit 793d41d841e5fb924409f4d6f2a6ec59c34a77a1

**Comment by dtschump** [comment]
Thanks for the report. Do you have any additional information to share ? (maybe what kind of webcam do you have?)
`zart` is working as expected for us, the more details we get, the more easy it will be to reproduce the bug.

**Comment by antonio-rojas** [comment]
`Bus 001 Device 002: ID 04f2:b5a4 Chicony Electronics Co., Ltd EasyCamera`

Reproduced with both Qt 5.14.1 and 5.15 beta 2.

**Comment by antonio-rojas** [comment]
Removing the call to `gmic::init_rc()` from ZArt.cpp fixes the problem here.

**Comment by dtschump** [comment]
> Removing the call to gmic::init_rc() from ZArt.cpp fixes the problem here.

Ah that reminds me some valgrind warnings I've fixed a few days ago. There was a missing '\0' at the end of a string, using in `gmic::init_rc()`.
Would it be possible you try once again with the latest sources in the git repo ? (not the one for  `zart`, but the one for `gmic`). I'm almost sure this is related.

**Comment by antonio-rojas** [comment]
[test.zip](https://github.com/c-koi/zart/files/4375099/test.zip)

It still fails with current gmic git.
I've attached a minimal test case. Compiling with
```
g++ -c -Dcimg_display=0 -o FT.o FT.cpp
g++ -c -o WS.o WS.cpp
g++ -c -o test.o test.cpp
g++ -o test test.o FT.o WS.o -lgmic -pthread
```
the produced binary segfaults at the second call to `W::WL()`. However, if you replace the last step with
```
g++ test.o WS.o FT.o -o test -lgmic -pthread
```
it no longer segfaults.

**Comment by dtschump** [comment]
That is strange...
If I don't link with `lgmic` but recompile the libgmic.o and add it for the link, it works also.
Here's my Makefile entry for testing:
~~~~
bug:
	make OPT_CFLAGS="-g" OPT_LIBS="" lib
	g++ -c -Dcimg_display=0 -o FT.o FT.cpp -g
	g++ -c -o WS.o WS.cpp -g
	g++ -c -o test.o test.cpp -g
	g++ -o test test.o FT.o WS.o libgmic.o -pthread -g -fopenmp -lpng -ljpeg -ltiff -lz -lfftw3 -lfftw3_threads -lX11 -lcurl
#	g++ -o test test.o FT.o WS.o -lgmic -pthread
~~~~
then:
~~~~
$ make bug
$ ./test 
aaaa
bbbb
~~~~

Maybe something wrong when the libgmic.so file is created? No idea for the moment.

**Comment by dtschump** [comment]
Another info. If I compile 'libgmic.so' without optimization flags, i.e. with `make OPT_CFLAGS="-g" OPT_LIBS="" lib`, then your test does work also with dynamic linking.

**Comment by dtschump** [comment]
So right now, I suspect the optimization flags to play a role in this. Trying to remove the `-flto` flags when compiling the lib, we'll see what happens.

**Comment by dtschump** [comment]
Flags `-O3` and `-Ofast` make it crash. `-O2` just works fine.
Still trying to figure out why.

**Comment by dtschump** [comment]
Spent most of my afternoon experimenting, and the conclusions are:
- In your example, the crash is due to the combination of two things:
   - The call to `cimg::mutex(28)` and `cimg::mutex(28,0)`, in function `gmic::path_rc()`.
**AND**
  - The use of the optimization flags `-O3` or `-Ofast`.

If I remove the calls to `cimg::mutex()`, or if I compiler with `-O2`, then your example code succeeds without issues.
At this point, I have no explanations about the issue. I don't see any problem with the current G'MIC/CImg code. I strongly suspect the optimizer to be a bit aggressive and mess with the static variable `struct Mutex_static val;` defined in `CImg.h` (l. 3193), used by inline function `cimg::Mutex_attr()` (which is itself called by `cimg::mutex()`).

I can't reasonably remove the call to `cimg::mutex()` in `gmic::path_rc()`. It is useful and in any ways, `cimg::mutex()` is called in many other locations in G'MIC code, so I'm afraid the issue will be the same for those calls.

So what I'm planning is to enable '-O2' for the default optimization flags, and use only '-Ofast' when it proved to work without issues (the cli tool and the plug-in seems to be OK with that).

**Comment by dtschump** [comment]
This commit : https://github.com/dtschump/gmic/commit/53b06f6e5e9a0595e687ac43342bcf3a7fd689a3

fixes the issue for me.

**Comment by antonio-rojas** [comment]
With 2.9.0, this is fixed on the gmic side, but zart still segfaults if I compile it with -O2 (our distro default). If I remove the -O2 flag for zart (not for gmic) it works.

**Comment by dtschump** [comment]
Another weird thing :)

I don't know what is going on, here my ZArt is working quite well (Ubuntu 19.10).
If you have any additional information (debug logs,...) do not hesitate to share.
